linters:
  enable:
    - errorlint
    - err113
    - exhaustruct
    - gocritic
    - gofmt
    - nilnil
    - nlreturn
    - wrapcheck
    - wsl
linters-settings:
  wrapcheck:
    ignorePackageGlobs:
      - github.com/couchbaselabs/gocbconnstr
    ignoreInterfaceRegexps:
      - "analyticsRowReader"
      - "queryClient"
